FROM alpine:latest

RUN apk update
RUN apk --no-cache add postfix
RUN apk --no-cache add dovecot
RUN apk --no-cache add nsd
RUN apk --no-cache add amavisd-new
RUN apk --no-cache add clamav
RUN apk --no-cache add spamassassin
RUN apk --no-cache add certbot
